In [ ]:
def add(*args):
  tmp=0

  for number in args:
    tmp=tmp+number
  
  return tmp

temp=add(1,2,22,12,17,21)

In [ ]:
print(temp)

75


In [ ]:
def add(**args):
  print(type(args))
  tmp=0

  for key in args:
    tmp=tmp+args[key]
  
  return tmp

temp=add(a=1,b=2,c=3,d=4)
print(temp)

<class 'dict'>
10


In [ ]:
print("Please input your number:")
number=int(input())

Please input your number:
5


In [ ]:
temp=number

In [ ]:
while number>1:
  number-=1
  temp=temp*number

In [ ]:
temp

120

In [ ]:
def factorial(number):
  if number==0:
    return 1
  else:
    return number*factorial(number-1)

In [ ]:
number=int(input())
print(factorial(number))

10
3628800


In [ ]:
mean= lambda a,b,c:((a+b+c)/3)

In [ ]:
print(mean(1,7,9))

5.666666666666667


In [ ]:
my_list=[2,3,4,5,6,7]

In [ ]:
def square(x):
  return x*x

In [ ]:
new_list=map(square,my_list)

In [ ]:
print(list(new_list))

[4, 9, 16, 25, 36, 49]


In [ ]:
a,b=map(int,input().split())

10 20


In [ ]:
a+b

30

In [ ]:
my_list=[2,3,4,5,6,7,8]

In [ ]:
def is_even(x):
  if (x%2)==0:
    return True
  else:
    return False

new_list=filter(is_even,my_list)
print(new_list)

In [ ]:
print(list(new_list))

[2, 4, 6, 8]


In [ ]:
a,b,c=map(int,input().split())

10 12 14


In [ ]:
max(a,b,c)

14

In [ ]:
if a>b & a>c:
  print(a)
elif b>a & b>c:
  print(b)
else:
  print(c)

14


In [ ]:
def iterator(start, end):
    pass

# iterator(10, 10)
# #iterator(start=10,20)
# #iterator(10,end=10)
# iterator(start=10,end=20)

In [ ]:
iterator(10,10)

In [ ]:
iterator(start=10,20)

SyntaxError: ignored

In [ ]:
iterator(10,end=10)

In [ ]:
iterator(start=10,end=20)

In [ ]:
lab_name = "NSLab"

In [ ]:
lab_name[0]='n'

TypeError: ignored

In [ ]:
def do_math(number1,number2):
  try:
    return (number1/number2)
  except ZeroDivisionError:
    return print("y is zero")

In [ ]:
do_math(1,2)

0.5

In [ ]:
do_math(1,0)

y is zero


In [ ]:
_v=5

In [ ]:
_v

5

In [ ]:
class LaptopBrand:
  def __init__(self,name):
    self._name=name
  def __repr__(self):
        return "LaptopBrand([{}, {}, {}, {}])".format(*self._floors)

  def __setitem__(self, item_number,data):
        self._name[item_number] = data
    
  def __getitem__(self, item_number):
        return self._name[item_number]

In [ ]:
laptopBrand = LaptopBrand("Lenovo")

# but how can i do this
laptopBrand[0] = 'DELL'
laptopBrand[1] = 'HP'

print(laptopBrand[0])

TypeError: ignored

In [ ]:
# super class
class Image:
    def __init__(self, width, height):
        self.width = width
        self.height = height

# child class
class FlowerImage(Image):
    def __init__(self, width, height, flower_name):
        super().__init__(width, height, flower_name)

In [ ]:
def fib(n):
  a=0
  b=1
  a,b=b,a+b
  if a==n:
    break
  return a

SyntaxError: ignored

In [ ]:
A = [[ 0,  1,  2,  3],
[ 4,  5,  6,  7],
[ 8,  9, 10, 11],
[12, 13, 14, 15]]

In [ ]:
type(A)

list

In [ ]:
import numpy as np
A=np.arange(16).reshape(4,4)

In [ ]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
A[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
A[:,:-1]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
A[1:,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
A = [[[[ 0,  1,  2],
        [ 3,  4,  5]],

        [[ 6,  7,  8],
        [ 9, 10, 11]]],


        [[[12, 13, 14],
        [15, 16, 17]],

        [[18, 19, 20],
        [21, 22, 23]]]]

In [ ]:
A=np.array(((((0,1,2),(3,4,5)),
           ((6,7,8),(9,10,11))),
           (((12,13,14),(15,16,17)),
            ((18,19,20),(21,22,23)))))

In [ ]:
A

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [ ]:
a=sum(A[0][0][0])

In [ ]:
b=sum(A[0][0][1])

In [ ]:
c=sum(A[0][1][0])

In [ ]:
d=sum(A[0][1][1])

In [ ]:
e=sum(A[1][0][0])

In [ ]:
f=sum(A[1][0][1])

In [ ]:
g=sum(A[1][1][0])

In [ ]:
h=sum(A[1][1][1])

In [ ]:
h

66

In [ ]:
Row_sum=np.array((((a,b),(c,d)),((e,f),(g,h))))

In [ ]:
Row_sum

array([[[ 3, 12],
        [21, 30]],

       [[39, 48],
        [57, 66]]])